highlighter: pygments
baseurl: /blog
default_page_title: 'Ty Riley | Blank Space'
markdown: redcarpet
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
